# Generated by Django 4.1.3 on 2022-12-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price_full', models.IntegerField(verbose_name='Price full')),
                ('price_par', models.IntegerField(verbose_name='Price partial')),
                ('full_text_uz', models.TextField(verbose_name='Full text uz')),
                ('full_text_ru', models.TextField(verbose_name='Full text ru')),
                ('full_text_en', models.TextField(verbose_name='Full text en')),
                ('par_text_uz', models.TextField(verbose_name='Partial text uz')),
                ('par_text_ru', models.TextField(verbose_name='Partial text ru')),
                ('par_text_en', models.TextField(verbose_name='Partial text en')),
                ('photo', models.CharField(max_length=255, verbose_name='Photo')),
            ],
            options={
                'db_table': 'menu_dinner',
            },
        ),
        migrations.CreateModel(
            name='MenuLunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price_full', models.IntegerField(verbose_name='Price full')),
                ('price_par', models.IntegerField(verbose_name='Price partial')),
                ('full_text_uz', models.TextField(verbose_name='Full text uz')),
                ('full_text_ru', models.TextField(verbose_name='Full text ru')),
                ('full_text_en', models.TextField(verbose_name='Full text en')),
                ('par_text_uz', models.TextField(verbose_name='Partial text uz')),
                ('par_text_ru', models.TextField(verbose_name='Partial text ru')),
                ('par_text_en', models.TextField(verbose_name='Partial text en')),
                ('photo', models.CharField(max_length=255, verbose_name='Photo')),
            ],
            options={
                'db_table': 'menu_lunch',
            },
        ),
        migrations.CreateModel(
            name='MerchatTransactionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255, null=True)),
                ('transaction_id', models.CharField(max_length=255, null=True)),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('time', models.BigIntegerField(blank=True, null=True)),
                ('perform_time', models.BigIntegerField(default=0, null=True)),
                ('cancel_time', models.BigIntegerField(default=0, null=True)),
                ('state', models.IntegerField(default=1, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at_ms', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(verbose_name='Order id')),
                ('user_id', models.BigIntegerField(verbose_name='User telegram_id')),
                ('full_name', models.CharField(max_length=50, verbose_name='Name of User')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone of User')),
                ('menu_id', models.IntegerField(verbose_name='Menu id')),
                ('menu_type', models.CharField(default='full', max_length=10, verbose_name='Menu type')),
                ('address_lat', models.FloatField(null=True, verbose_name='Address latitude')),
                ('address_lon', models.FloatField(null=True, verbose_name='Address longitude')),
                ('comment', models.CharField(max_length=255, null=True, verbose_name='Comment')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('event', models.CharField(default='lunch', max_length=10, null=True, verbose_name='Event')),
                ('order_time', models.DateTimeField(null=True, verbose_name='Order time')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
